<?php
    /* @var $this Clean_SqlReports_Block_Adminhtml_Report_Chart */
    $report = $this->_getReport(); /* @var $report Clean_SqlReports_Model_Report */
?>

<script type="text/javascript" src="https://www.google.com/jsapi"></script>
<script type="text/javascript">

<?php if ($report->getOutputType() == Clean_SqlReports_Model_Config_OutputType::TYPE_CALENDAR_CHART): ?>
    google.load("visualization", "1.1", {packages:["calendar"]});
<?php elseif ($report->getOutputType() == Clean_SqlReports_Model_Config_OutputType::TYPE_GEO_CHART): ?>
    google.load('visualization', '1.0', {'packages': ['geochart']});
<?php else: ?>
    google.load('visualization', '1.0', {'packages': ['corechart']});
<?php endif; ?>

google.setOnLoadCallback(function() {
    new Ajax.Request('<?php echo Mage::helper("adminhtml")->getUrl('adminhtml/adminhtml_report/getJson',array('report_id' => $report->getId())) ?>', {
        method:'get',
        onSuccess: function(transport) {
            var jsonData = transport.responseText.evalJSON();
            if (jsonData.error) {
                alert(jsonData.error)
            } else {

                <?php if ($report->getOutputType() == Clean_SqlReports_Model_Config_OutputType::TYPE_CALENDAR_CHART): ?>
                var data = new google.visualization.DataTable();
                data.addColumn({ type: 'date', id: 'Date' });
                data.addColumn({ type: 'number', id: 'Test' });

                for (var i in jsonData) {
                    jsonData[i][0] = new Date(jsonData[i][0] * 1000);
                }
                data.addRows(jsonData);

                <?php else: ?>
                    var data = google.visualization.arrayToDataTable(jsonData);
                <?php endif; ?>

                var chart = new google.visualization.<?php echo $report->getOutputType(); ?>(document.getElementById('<?php echo $report->getChartDiv(); ?>'));
                chart.draw(data, <?php echo $report->getChartConfig() ? $report->getChartConfig() : '{}'; ?>);
            }
        }
    });
});
</script>

<div id="<?php echo $report->getChartDiv(); ?>"></div>


