<?php
/* @var $this Clean_SqlReports_Block_Adminhtml_Chart_View */
$chart = $this->getChart();
?>

<script type="text/javascript" src="https://www.google.com/jsapi"></script>
<script type="text/javascript">

<?php if ($chart->getOutputType() == Clean_SqlReports_Model_Config_OutputType::TYPE_CALENDAR_CHART): ?>
    google.load("visualization", "1.1", {packages:["calendar"]});
<?php elseif ($chart->getOutputType() == Clean_SqlReports_Model_Config_OutputType::TYPE_GEO_CHART): ?>
    google.load('visualization', '1.0', {'packages': ['geochart']});
<?php else: ?>
    google.load('visualization', '1.0', {'packages': ['corechart']});
<?php endif; ?>

google.setOnLoadCallback(function() {
    new Ajax.Request('<?php echo Mage::helper("adminhtml")->getUrl('*/*/json',array('_current' => true)) ?>', {
        method:'get',
        onSuccess: function(transport) {
            var jsonData = transport.responseText.evalJSON();
            if (jsonData.error) {
                alert(jsonData.error)
            } else {

                <?php if ($chart->getOutputType() == Clean_SqlReports_Model_Config_OutputType::TYPE_CALENDAR_CHART): ?>
                var data = new google.visualization.DataTable();
                data.addColumn({ type: 'date', id: 'Date' });
                data.addColumn({ type: 'number', id: 'Test' });

                for (var i in jsonData) {
                    jsonData[i][0] = new Date(jsonData[i][0] * 1000);
                }
                data.addRows(jsonData);

                <?php else: ?>
                    var data = google.visualization.arrayToDataTable(jsonData);
                    <?php endif; ?>

                    var chart = new google.visualization.<?php echo $chart->getOutputType(); ?>(document.getElementById('<?php echo $chart->getChartDiv(); ?>'));
                    chart.draw(data, <?php echo $chart->getChartConfig() ? $chart->getChartConfig() : '{}'; ?>);
                }
            }
        });
    });
</script>

<div id="<?php echo $chart->getChartDiv(); ?>"></div>


